doctrine:
  dbal:
    default_connection: data
    connections:
      data:
        url: '%env(resolve:DATABASE_URL)%'
      infra:
        url: '%env(resolve:INFRA_DATABASE_URL)%'
  orm:
    auto_mapping: false
